version: '3.8'
services:
  authpp:
    # stdin_open: true
    # tty: true
    build: 
      context: ./packages/auth
      dockerfile: Dockerfile.dev
    image: micronyks/authapp-dev:1.0.0
    container_name: auth
    ports:
      - "3001:3001"
    # volumes:
    #   - ./packages/auth:/app
    environment:
      - CHOCKIDAR_USEPOLLING=true
  
  commonapp:
    build: 
      context: ./packages/common
      dockerfile: Dockerfile.dev
    image: micronyks/commonapp-dev:1.0.0
    container_name: common
    ports:
      - "3002:3002"

  dashboardapp:
    build:
      context: ./packages/dashboard
      dockerfile: Dockerfile.dev
    image: micronyks/dashboardapp-dev:1.0.0
    container_name: dashboard
    ports:
      - "3003:3003"
    depends_on:
      - commonapp

  headerapp:
    build:
      context: ./packages/header
      dockerfile: Dockerfile.dev
    image: micronyks/headerapp-dev:1.0.0
    container_name: header
    ports:
      - "3004:3004"

  webapp:
    build: 
      context: ./packages/webapp
      dockerfile: Dockerfile.dev
    image: micronyks/webapp-dev:1.0.0
    container_name: webapp
    ports:
      - "3000:3000"
    depends_on:
      - authapp
      - commonapp
      - dashboardapp
      - headerapp
      - serverapp

  serverapp:
    build:
      context: ./packages/server
      dockerfile: Dockerfile.dev
    image: micronyks/serverapp-dev:1.0.0
    container_name: server
    ports:
      - "5000:5000"