name: deploy-docker-images-to-S3-bucket

on: [push]

# on:
#   push:
#     branches:
#       - main
#       - master
#     paths:
#       - 'packages/auth/**'

defaults:
  run:
    working-directory: packages/webapp

jobs:
  build:
    runs-on:  ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: docker build

        run: npm run docker 

      # - run: npm install
      # - run: npm run build

      - uses: shinyinc/action-aws-cli@v1.2
      - run: aws s3 sync dist-docker-images s3://${{ secrets.AWS_S3_BUCKET_NAME }}/docker-images
        env: 
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'ap-south-1'
