name: deploy-docker-images

on: [push]

# on:
#   push:
#     branches:
#       - main
#       - master
#     paths:
#       - 'docker-compose.yml'

# defaults:
#   run:
#     working-directory: docker-compose.yml

jobs:
  build:
    runs-on:  ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: docker login

        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

        run:
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

      - name: docker build auth-app

        run: |

          docker build ./packages/auth -t micronyks/webapp:1.0.0  -f Dockerfile.prod

      

      # - run: npm install
      # - run: npm run build

      # - uses: shinyinc/action-aws-cli@v1.2
      # - run: aws s3 sync dist s3://${{ secrets.AWS_S3_BUCKET_NAME }}/header/latest
      #   env: 
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     AWS_DEFAULT_REGION: 'ap-south-1'

      # - run: aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_DISTRIBUTION_ID }} --paths "/header/latest/remoteEntry.js"
      #   env: 
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     AWS_DEFAULT_REGION: 'ap-south-1'
