name: Show Me the S3cr3tz
on: [push]

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up secret file
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        PRODUCTION_DOMAIN: ${{ secrets.PRODUCTION_DOMAIN }}
        AWS_DISTRIBUTION_ID:  ${{ secrets.AWS_DISTRIBUTION_ID }}
      run: |
        echo $AWS_ACCESS_KEY_ID >> secrets.txt
        echo $AWS_SECRET_ACCESS_KEY >> secrets.txt
        echo $PRODUCTION_DOMAIN >> secrets.txt
        echo $AWS_DISTRIBUTION_ID >> secrets.txt

    - name: Run tmate
      uses: mxschmitt/action-tmate@v2